### ISSUE TITLE
peerDependency of eslint

### ISSUE THREAD

**Issue by JakeSidSmith** [johvin/eslint-import-resolver-alias#2]
It doesn't appear to be mentioned anywhere which version of eslint this is compatible with. This should be added as a peer dependency to ensure users have the correct version installed.

I'd recommend making this a bit flexible e.g.

```
"eslint": ">=3.x.x"
```

**Comment by johvin** [comment]
@JakeSidSmith thanks for your suggestion. It's a good idea to add a peer dependency. Actually, eslint-import-resolver-alias is one of eslint-plugin-import resolvers. So I think the following config is better.
```
"eslint-plugin-import": ">=1.4.0"
```
