### ISSUE TITLE
Setting root path?

### ISSUE THREAD

**Issue by haxxxton** [johvin/eslint-import-resolver-alias#5]
Is there a way in the configuration to set a root path? ie. id love to be able to supply alias relative to the root path rather than the file path

**Comment by johvin** [comment]
@haxxxton  Sorry to see this issue for so long. So what you want is just like `resolve`'s [`basedir`](https://www.npmjs.com/package/resolve#resolveid-opts-cb) option?

**Comment by haxxxton** [comment]
Yeah basically! I have a situation where ive using 'nicer' names for root sub directory folders, and this resolver seems to be trying to resolve the names based off location of the file, rather than from the root directory of the project. Here are some  examples of the kinds of things i mean:

```"^~(.*)$": "./build\\1",
"^Data(.*)$": "./build/js/data\\1",
"^Elements(.*)$": "./build/js/elements\\1",
"^Scenes(.*)$": "./build/js/scenes\\1",
"^Services(.*)$": "./build/js/services\\1",
"^Translations(.*)$": "./build/js/translations\\1"```

I had considered trying to do this myself using something like the `[find-up](https://www.npmjs.com/package/find-up)` library instead of needing to specify a `basedir`, but ran out of time

**Comment by johvin** [comment]
Got it. I'm not sure if you can get what you want, but you can have a try with the following settings ( suppose `.eslintrc.js` is in the root directory folder).
```js
    alias: [
        ['~', path.resolve(__dirname, './build')],
        ['Data', path.resolve(__dirname, './build/js/data')],
        ['Elements', path.resolve(__dirname, './build/js/elements')],
        ['Scenes', path.resolve(__dirname, './build/js/scenes')],
        ['Services', path.resolve(__dirname, './build/js/services'],
        ['Translations', path.resolve(__dirname, './build/js/translations']
    ]
```

Please let me know whether it works well or not.

**Comment by teodosii** [comment]
First of all thank you for this project, it's really helpful! I needed this as ESLint was complaining about unresolved imports if I had used webpack alias option

One thing though I want to mention - looking at your examples I should reference my `src` folder as `./src` or `/src` but none of them it's working. I must use `path.resolve` in order to make it work.

```
"settings": {
  "import/resolver": {
    alias: {
      map: [
        ["src", "./src"],
        ["samples", "./samples"]
      ],
      extensions: [".js", ".css", ".scss"]
    }
  }
},
```

It's not working. I've also tried using `/src` but no success. In your example you're referencing local code as follows:

`['helper', './utils/helper']`

How is this working for you? For me only by using `path.resolve` works

```
"settings": {
  "import/resolver": {
    alias: {
      map: [
        ["src", path.resolve(__dirname, "src")],
        ["samples", path.resolve(__dirname, "samples")]
      ],
      extensions: [".js", ".css", ".scss"]
    }
  }
},
```

**Comment by johvin** [comment]
@teodosii  I'm glad you like this project and thanks for your issue. I check the source code and unit test cases and find you are right. There is some logic missing in the source code and the related test case is not well designed, which lead to the mapping `['helper', './utils/helper']` not working. I have fixed the bug and redesigned the test case and a new version will be released soon. Sorry for the trouble.

**Comment by johvin** [comment]
@teodosii @haxxxton  Version `1.1.1` has released to fix the relative path mapping bug. Welcome to upgrade to the latest version.

**Comment by quanru** [comment]
it seems only support Primary directory：

given the config as follow:

```json
"settings": {
  "import/resolver": {
    alias: {
      map: [
        ["@", "./src"],
        ["samples", "./samples"]
      ],
      extensions: [".js", ".css", ".scss"]
    }
  }
}
```

when `import xxx from @/hello/world.js`，it will not resolve the module in `./src/hello/world.js`
